version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    env_file:
      - .env
