

services:
  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo
      - rabbitmq 
    volumes:
      - .:/app

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    env_file:
      - .env
      
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  consumer:
    build: .
    command: node consumer.js  
    depends_on:
      - rabbitmq
    volumes:
      - .:/app